name: Backend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'

defaults:
  run:
    working-directory: starter/backend

env:
  PYTHON_VERSION: '3.10'
  AWS_REGION: us-east-1
  ECR_REPOSITORY: backend
  EKS_CLUSTER_NAME: cluster

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: