name: Frontend Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

defaults:
  run:
    working-directory: starter/frontend

env:
  NODE_VERSION: '18'
  AWS_REGION: us-east-1
  ECR_REPOSITORY: frontend
  EKS_CLUSTER_NAME: cluster

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: CI=true npm test

  build-and-deploy:
    name: Build and Deploy
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('starter/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{  ASIAUOS5XUARZDFKRQON }}
          aws-secret-access-key: ${{  F6q4SSSH0BDlDyXHaDCz3otdzOFkhJSBKihfk/8m }}
          aws-session-token: ${{ IQoJb3JpZ2luX2VjEG0aCXVzLXdlc3QtMiJHMEUCIQCtVXeqSCAuAmH2B6Tf3tJK9FigXmaW6D9THmcxXcNd0gIgChgG6sxPuRPJX/v1P2KOZBCjA9MyWPQj1g8t3Asf7f4qvgIINhADGgwzMDYyMTMwMDMyOTkiDHVLuegh3qnZFqawtiqbApGPIBHRT0+X2hR212tEqxsXHtDcBa6FPMNvh8NfRj+9ZZhQf0AcA4dWyBmFKPYi1PyETVuQCvcxN6i11kpQpEO8jhcdXmbFdM0/V42pK9FStXuFND1YqTVh/W1LMaK+OBIreSES7Efa7WU63vJ8KrZsa0KWTKNaUamALHImAIRixA5b9XjRWdq9ZZB2yuwL2PwmeLwfkR3FJhXKsuvtlFu1TE//Zl3UnceKaseLBVSYf9JGOV1WMKJIu3kypb4uu7ZuaDU5rnipXTpnA5lQoAxpMfLU8pluXx6dfr395xKt7jmb6Ob4x9KS88alII0szwKJjtz7+Etcxl3AsGgD8hXehaBPZFEb89jYbIIqD3fg9+wVN/b6K3FaFGgw8rjp1QY6nQF3cgGz7f99ThGjCUh49gXptnZ2ehR+aObfKvtsAu1r1HqEqis+8ayCehf3nJGk4xsaVoI9zaSeIP6QR1EYHQqG7ytbkHByFCzCx97ifzhLu++iQp9Hdni+v6JikL/IvGqw0YI8QOkgptHNLTMwlLbsbCHVriOYcv6eDsQWeSGdhfWWCQk4hlVy2Td2nXwz1j6NmKLcNI+xE/woVuD0
 }}
          aws-region: ${{ us-east-1}}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          REACT_APP_MOVIE_API_URL: http://localhost:5000
        run: |
          docker build \
            --build-arg=REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL \
            --tag=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --tag=$ECR_REGISTRY/$ECR_REPOSITORY:latest
